logging:
  level:
   #打印SQL信息
   top.kinglf.dataservice.service.jms: debug


rocketmq:
  producer:
    # 发送同一类消息的设置为同一个group，保证唯一,默认不需要设置，rocketmq会使用ip@pid(pid代表jvm名字)作为唯一标示
    groupName: ProducerGroup_dataservice
    #mq的nameserver地址
    namesrvAddr: 127.0.0.1:9876
    #如果需要同一个jvm中不同的producer往不同的mq集群发送消息，需要设置不同的instanceName
    instanceName: ProducerGroup_dataservice
    #topic名称
    topic: WaitParser
    #消息最大长度
    maxMessageSize: 131072 # 1024*128
    #发送消息超时时间
    sendMsgTimeout: 10000
server:
  port: 9090